#!/bin/bash
# This launcher is needed to wrap the main script, so it inherits the directory path from the shell. Lua 5.1 cannot get the script path by itself reliably, and that brings a lot of stability issues
# With this launcher, you can start the program from any location, as long as remains in the project root folder
original_directory=$(pwd)
# dirname $0 cannot be called directly, or it will return "." when called from the project directory
# Moving to the parent directory and then printing it allows saving the full root directory location to a variable
root_directory=$(cd "$(dirname "$0")" && pwd)
cd $root_directory
# All arguments are passed intact with "$@"
# In Unix-like systems, you must customize this variable to point to a valid Lua 5.1 interpreter, either:
# - Installed from a package manager
# - Downloaded as a binary from an official source. Suggested, from LuaBinaries' Source Forge repository
# https://sourceforge.net/projects/luabinaries/files/5.1.5/Tools%20Executables/
lua_alias="lua5.1"
"$lua_alias" ./main.lua "$@"
cd $original_directory